[GUI][Trivial] Rewording of Error message while trying to send with the transaction with wallet unlocked for staking only
Not sure if this is good or it needs to be:

> Error: The wallet is unlocked for anonymization and staking only.**\n**Unlock the wallet to send the transaction.